### ISSUE TITLE
DC-Metro-Pi-Speaker demo?

### ISSUE THREAD

**Issue by mvs202** [astrowonk/DC-Metro-Pi-Speaker#4]
any chance you might want to demo at next [Transportation Techies](http://www.meetup.com/Transportation-Techies/) MetroHackNight?

**Comment by astrowonk** [comment]
Hi, thanks for the invitation! The only issue is ... the code doesn't work that well at the moment. Google text to speech has some sort of throttling so I can't actually use this program anymore - Google throws up a captcha that the python library can't get by - I've been meaning to implement some other text to speech options but I haven't had the time. It might work if I moved the Pi and thus changed the iP address but anyone using it regularly would eventually encounter the same bug.

**Comment by astrowonk** [comment]
hey @mvs202 - the code works again! the next metro hacknight could be fun, if I'm in town!
